/**
 * Created by nnoman on 14.07.2022.
 */
@IsTest
public with sharing class TEST_WebinarEmailNotificationScheduler
{
    @TestSetup
    private static void makeData()
    {
//        Webinar__c webinar = new Webinar__c();
//        webinar.Start_Date__c=Date.today().addDays(1);
//        insert webinar;
//
//        Contact contact= new Contact();
//////        create contact
////        contact.MailingCity='lol';
////        contact.MailingCountry='lol';
////        contact.MailingCountryCode='pl';
////        contact.MailingStreet='lol';
//        insert contact;
//
//        Webinar_Team_Member__c webinarTeamMember = new Webinar_Team_Member__c();
//        webinarTeamMember.Related_Webinar__c=webinar.Id;
//        webinarTeamMember.Contact__c=contact.Id;

    }

//    @IsTest
//    priv
}